### ISSUE TITLE
java.io.IOException: Could not find resource mybatis-config.xml

### ISSUE THREAD

**Issue by XUAN-CW** [homejim/mybatis-examples#25]
# 错误描述

```
java.io.IOException: Could not find resource mybatis-config.xml
```

但明明 **mybatis-config.xml** 就在那里，为什么会错？

# 原因

没有指定 **resources** 文件夹为 **Resources Root** 

# 解决方法

![2021-07-15_204310](https://user-images.githubusercontent.com/49336037/125791529-0403b521-1a98-423d-a8f2-91f4a0b122c4.png)

**Comment by googlg** [comment]
这是为啥呢。我把 src/main/resources 中的资源与配置文件 copy一份到了  src/test/resources 中可以解决，但这样要维护两份。

在 pom中添加
`   <testResources>
      <testResource><directory>src/test/resources</directory></testResource>
      <testResource><directory>src/main/resources</directory></testResource>
    </testResources>`
也不行
